-- =============================================================================
-- SIMULATED DATA — every row in this schema is fictional and generated by
-- make_db.py with a fixed random seed. No real people, companies, or figures.
-- =============================================================================

CREATE TABLE customers (
    customer_id  INTEGER PRIMARY KEY,
    full_name    TEXT NOT NULL,
    city         TEXT NOT NULL,
    signup_date  TEXT NOT NULL          -- ISO-8601 date (YYYY-MM-DD)
);

CREATE TABLE campaigns (
    campaign_id    INTEGER PRIMARY KEY,
    campaign_name  TEXT NOT NULL,
    channel        TEXT NOT NULL,       -- Email | Social | Search | Display
    start_date     TEXT NOT NULL,
    end_date       TEXT NOT NULL,
    spend          REAL NOT NULL        -- fictional ad spend in USD
);

CREATE TABLE orders (
    order_id     INTEGER PRIMARY KEY,
    customer_id  INTEGER NOT NULL REFERENCES customers(customer_id),
    campaign_id  INTEGER REFERENCES campaigns(campaign_id),
    order_date   TEXT NOT NULL,         -- ISO-8601 date (YYYY-MM-DD)
    category     TEXT NOT NULL,         -- Apparel | Electronics | Home | Beauty | Sports
    amount       REAL NOT NULL          -- fictional order total in USD
);

-- Indexes: the cost estimator uses these to distinguish indexed access
-- (SEARCH ... USING ...) from full table scans (SCAN ...).
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_campaign ON orders(campaign_id);
CREATE INDEX idx_orders_date     ON orders(order_date);
CREATE INDEX idx_customers_city   ON customers(city);
